# Sales Data Analysis using Python & Pandas

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("sales_data.csv")

In [ ]:
# Display first 5 records
print("\n===== FIRST 5 RECORDS =====")
print(df.head())

,Order ID,Product Name,Category,Quantity,Price,Total Amount,Date
0,1001,Laptop,Electronics,2,80000,160000,2026-07-01
1,1002,Mouse,Electronics,5,1500,7500,2026-07-02
2,1003,Office Chair,Furniture,3,12000,36000,2026-07-03
3,1004,Notebook,Stationery,20,250,5000,2026-07-04
4,1005,Printer,Electronics,1,35000,35000,2026-07-05

In [ ]:
# Display last 5 records
print("\n===== LAST 5 RECORDS =====")
print(df.tail())

,Order ID,Product Name,Category,Quantity,Price,Total Amount,Date
20,1021,Coffee Table,Furniture,2,15000,30000,2026-07-21
21,1022,Webcam,Electronics,4,7000,28000,2026-07-22
22,1023,File Folder,Stationery,25,150,3750,2026-07-23
23,1024,Bookshelf,Furniture,2,26000,52000,2026-07-24
24,1025,Smartphone,Electronics,3,90000,270000,2026-07-25

In [17]:
# Dataset information
print("\n===== DATASET INFORMATION =====")
df.info()

===== DATASET INFORMATION =====
<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      25 non-null     int64
 1   Product Name  25 non-null     str
 2   Category      25 non-null     str
 3   Quantity      25 non-null     int64
 4   Price         25 non-null     int64
 5   Total Amount  25 non-null     int64
 6   Date          25 non-null     str
dtypes: int64(4), str(3)
memory usage: 2.2 KB

In [16]:
# Total sales amount
total_sales = df["Total Amount"].sum()
print("\nTotal Sales Amount:")
print(total_sales)

Total Sales Amount:
1083650

In [15]:
# Average sales amount
average_sales = df["Total Amount"].mean()
print("\nAverage Sales Amount:")
print(round(average_sales, 2))

Average Sales Amount:
43346.0

In [14]:
# Product with highest sales
highest_sale = df.loc[df["Total Amount"].idxmax()]
print("\n===== PRODUCT WITH HIGHEST SALES =====")
print(highest_sale)

===== PRODUCT WITH HIGHEST SALES =====
Order ID               1025
Product Name     Smartphone
Category        Electronics
Quantity                  3
Price                 90000
Total Amount         270000
Date             2026-07-25
Name: 24, dtype: object

In [18]:
# Best-selling category
best_category = (
    df.groupby("Category")["Total Amount"]
      .sum()
      .idxmax()
)
print("\nBest Selling Category:")
print(best_category)

Best Selling Category:
Electronics

In [22]:
# Sales greater than 5000
print("\n===== SALES GREATER THAN 5000 =====")
high_sales = df[df["Total Amount"] > 5000]
high_sales

===== SALES GREATER THAN 5000 =====

,Order ID,Product Name,Category,Quantity,Price,Total Amount,Date
0,1001,Laptop,Electronics,2,80000,160000,2026-07-01
1,1002,Mouse,Electronics,5,1500,7500,2026-07-02
2,1003,Office Chair,Furniture,3,12000,36000,2026-07-03
4,1005,Printer,Electronics,1,35000,35000,2026-07-05
5,1006,Desk,Furniture,2,18000,36000,2026-07-06
7,1008,Monitor,Electronics,2,40000,80000,2026-07-08
8,1009,Bookshelf,Furniture,1,25000,25000,2026-07-09
9,1010,Keyboard,Electronics,4,2500,10000,2026-07-10
10,1011,Calculator,Stationery,6,1800,10800,2026-07-11
11,1012,Table,Furniture,2,22000,44000,2026-07-12
12,1013,Headphones,Electronics,3,6000,18000,2026-07-13
13,1014,Whiteboard,Stationery,2,4500,9000,2026-07-14
14,1015,Sofa,Furniture,1,75000,75000,2026-07-15
15,1016,USB Drive,Electronics,10,1200,12000,2026-07-16
17,1018,Cabinet,Furniture,2,28000,56000,2026-07-18
18,1019,Projector,Electronics,1,65000,65000,2026-07-19
19,1020,Diary,Stationery,18,500,9000,2026-07-20
20,1021,Coffee Table,Furniture,2,15000,30000,2026-07-21
21,1022,Webcam,Electronics,4,7000,28000,2026-07-22
23,1024,Bookshelf,Furniture,2,26000,52000,2026-07-24
24,1025,Smartphone,Electronics,3,90000,270000,2026-07-25

In [23]:
# Sort by total amount
sorted_df = df.sort_values(
    by="Total Amount",
    ascending=False
)

print("\n===== SORTED DATASET =====")
sorted_df

===== SORTED DATASET =====

,Order ID,Product Name,Category,Quantity,Price,Total Amount,Date
24,1025,Smartphone,Electronics,3,90000,270000,2026-07-25
0,1001,Laptop,Electronics,2,80000,160000,2026-07-01
7,1008,Monitor,Electronics,2,40000,80000,2026-07-08
14,1015,Sofa,Furniture,1,75000,75000,2026-07-15
18,1019,Projector,Electronics,1,65000,65000,2026-07-19
17,1018,Cabinet,Furniture,2,28000,56000,2026-07-18
23,1024,Bookshelf,Furniture,2,26000,52000,2026-07-24
11,1012,Table,Furniture,2,22000,44000,2026-07-12
2,1003,Office Chair,Furniture,3,12000,36000,2026-07-03
5,1006,Desk,Furniture,2,18000,36000,2026-07-06
4,1005,Printer,Electronics,1,35000,35000,2026-07-05
20,1021,Coffee Table,Furniture,2,15000,30000,2026-07-21
21,1022,Webcam,Electronics,4,7000,28000,2026-07-22
8,1009,Bookshelf,Furniture,1,25000,25000,2026-07-09
12,1013,Headphones,Electronics,3,6000,18000,2026-07-13
15,1016,USB Drive,Electronics,10,1200,12000,2026-07-16
10,1011,Calculator,Stationery,6,1800,10800,2026-07-11
9,1010,Keyboard,Electronics,4,2500,10000,2026-07-10
19,1020,Diary,Stationery,18,500,9000,2026-07-20
13,1014,Whiteboard,Stationery,2,4500,9000,2026-07-14
1,1002,Mouse,Electronics,5,1500,7500,2026-07-02
3,1004,Notebook,Stationery,20,250,5000,2026-07-04
22,1023,File Folder,Stationery,25,150,3750,2026-07-23
16,1017,Marker Set,Stationery,12,300,3600,2026-07-17
6,1007,Pen Pack,Stationery,15,200,3000,2026-07-07

In [21]:
# Save analyzed dataset
sorted_df.to_csv(
    "sales_data_analyzed.csv",
    index=False
)
print("\nAnalyzed dataset saved successfully.")

Analyzed dataset saved successfully.